name: ci
permissions:
  contents: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}
jobs:
  build-info:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.info.outputs.date }}
      commit_hash: ${{ steps.info.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get build info
        id: info
        shell: bash
        run: |
          echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
          echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
  build:
    needs: build-info
    strategy:
      matrix:
        include:
          - target: { os: 'windows', arch: 'x86_64' }
            runner: ubuntu-latest
          - target: { os: 'windows', arch: 'x86' }
            runner: ubuntu-latest
          - target: { os: 'windows', arch: 'aarch64' }
            runner: ubuntu-latest
          - target: { os: 'macos', arch: 'x86_64' }
            runner: macos-13
          - target: { os: 'macos', arch: 'aarch64' }
            runner: macos-latest
          - target: { os: 'linux', arch: 'x86_64' }
            runner: ubuntu-latest
          - target: { os: 'linux', arch: 'x86' }
            runner: ubuntu-latest
          - target: { os: 'linux', arch: 'aarch64' }
            runner: ubuntu-latest
          - target: { os: 'linux', arch: 'riscv64' }
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: Setup macOS SDK (macOS only)
        if: matrix.target.os == 'macos' && runner.os == 'macOS'
        run: |
          # Ensure Xcode command line tools are available
          sudo xcode-select --install 2>/dev/null || true
          # Set SDK path for Zig
          echo "ZIG_GLOBAL_CACHE_DIR=$HOME/.cache/zig" >> $GITHUB_ENV
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      - name: Build
        env:
          BUILD_DATE: ${{needs.build-info.outputs.date}}
          COMMIT_HASH: ${{needs.build-info.outputs.commit_hash}}
        run: |
          if [[ "${{ matrix.target.os }}" == "macos" && "$RUNNER_OS" == "macOS" ]]; then
            # Native build on macOS - don't specify target to avoid cross-compilation issues
            if [[ "${{ matrix.target.arch }}" == "$(uname -m)" || ("${{ matrix.target.arch }}" == "aarch64" && "$(uname -m)" == "arm64") ]]; then
              zig build -Doptimize=ReleaseSafe -Dcpu=baseline
            else
              # Cross-compile within macOS (e.g., x86_64 on arm64 or vice versa)
              zig build -Dtarget=${{ matrix.target.arch }}-${{ matrix.target.os }} -Doptimize=ReleaseSafe -Dcpu=baseline
            fi
          else
            # Cross-compile for other platforms
            zig build -Dtarget=${{ matrix.target.arch }}-${{ matrix.target.os }} -Doptimize=ReleaseSafe -Dcpu=baseline
          fi
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: z8-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: zig-out/bin/z8${{ matrix.target.os == 'windows' && '.exe' || '' }}
  release:
    needs: [build-info, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Prepare Release Files
        run: |
          cd artifacts
          for dir in */; do
            if [ -f "$dir/z8.exe" ]; then
              (cd "$dir" && zip "../${dir%/}.zip" z8.exe)
            elif [ -f "$dir/z8" ]; then
              (cd "$dir" && zip "../${dir%/}.zip" z8)
            fi
          done
      - name: Delete all existing releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}/releases"
          
          releases=$(curl -H "Authorization: token $GITHUB_TOKEN" "$api_url")
          
          echo "$releases" | jq -c '.[]' | while read -r release; do
            release_id=$(echo "$release" | jq -r '.id')
            release_tag=$(echo "$release" | jq -r '.tag_name')
            
            echo "Deleting release: $release_id with tag: $release_tag"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "$api_url/$release_id"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$release_tag"
          done
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "z8-${{ needs.build-info.outputs.date }}-${{ needs.build-info.outputs.commit_hash }}"
          tag: "z8-${{ needs.build-info.outputs.date }}-${{ needs.build-info.outputs.commit_hash }}"
          draft: false
          prerelease: false
          artifacts: "artifacts/*.zip"
          body: |
            Automated release for z8
